service: meraki-webhook
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
package:
  exclude:
    - node_modules/**
    - venv/**
provider:
  name: aws
  runtime: python3.6
  stage: production
  region: us-east-1
  environment:
    ORGANIZATION_ID: 755827
    ROLLBAR_ACCESS_KEY: 2d7bf8afa3f2406b8e97de3e0dd4713a
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
